CREATE TABLE UGYFEL_MASZKOLT (
    LOGIN VARCHAR(32),
    EMAIL VARCHAR(64),
    NEV VARCHAR(64),
    SZULEV NUMERIC(4,0),
    NEM VARCHAR(1),
    CIM VARCHAR(128)
);

INSERT INTO UGYFEL_MASZKOLT (LOGIN, EMAIL, NEV, SZULEV, NEM, CIM)
SELECT
    LOGIN,
    LEFT(EMAIL, 1) + '***' + SUBSTRING(EMAIL, CHARINDEX('@', EMAIL), LEN(EMAIL)) AS EMAIL,
    LEFT(NEV, 1) + REPLICATE('*', LEN(NEV) - 1) AS NEV,
    SZULEV,
    NEM,
    'RandomCim_' + CAST(ABS(CAST(NEWID() AS BINARY(6)) % 10000) AS VARCHAR(4)) AS CIM
FROM UGYFEL;

SELECT * FROM UGYFEL_MASZKOLT;

CREATE LOGIN webshop_user WITH PASSWORD = 'TitkosJelszo123!';
CREATE USER webshop_user FOR LOGIN webshop_user;

GRANT SELECT ON UGYFEL_MASZKOLT TO webshop_user;